# Generated by Django 6.0.2 on 2026-02-09 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام دستگاه")),
                ("config_json", models.JSONField(verbose_name="تنظیمات دستگاه (JSON)")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "دستگاه",
                "verbose_name_plural": "دستگاه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        max_length=255,
                        verbose_name="URL پروکسی (e.g. http://user:pass@ip:port)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "last_checked",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بررسی"),
                ),
                (
                    "status_code",
                    models.IntegerField(blank=True, null=True, verbose_name="کد وضعیت"),
                ),
            ],
            options={
                "verbose_name": "پروکسی",
                "verbose_name_plural": "پروکسی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="SearchEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام موتور جستجو"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "موتور جستجو",
                "verbose_name_plural": "موتورهای جستجو",
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام سایت")),
                ("main_url", models.URLField(verbose_name="آدرس اصلی سایت")),
                ("articles_url", models.URLField(verbose_name="آدرس بخش مقالات")),
                (
                    "search_engines_enabled",
                    models.BooleanField(
                        default=True, verbose_name="جستجو در موتورهای جستجو فعال باشد؟"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255, verbose_name="کلمه کلیدی")),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="bot_manager.siteconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلمه کلیدی",
                "verbose_name_plural": "کلمات کلیدی",
            },
        ),
        migrations.CreateModel(
            name="BotJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("running", "در حال اجرا"),
                            ("completed", "تکمیل شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="پیشرفت")),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="مرحله فعلی"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان شروع"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پایان"
                    ),
                ),
                ("log", models.TextField(blank=True, verbose_name="لاگ")),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_manager.siteconfig",
                        verbose_name="سایت",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملیات ربات",
                "verbose_name_plural": "عملیات\u200cهای ربات",
            },
        ),
    ]
