# Generated by Django 6.0.2 on 2026-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="لینک دریافت لیست پروکسی")),
                (
                    "last_sync",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین همگام\u200cسازی"
                    ),
                ),
            ],
            options={
                "verbose_name": "منبع پروکسی",
                "verbose_name_plural": "منابع پروکسی",
            },
        ),
    ]
