# Generated by Django 6.0.2 on 2026-02-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_manager", "0002_proxysource"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawledLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="آدرس")),
                (
                    "is_visited",
                    models.BooleanField(default=False, verbose_name="بازدید شده"),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان کشف"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawled_links",
                        to="bot_manager.siteconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک کرال شده",
                "verbose_name_plural": "لینک\u200cهای کرال شده",
            },
        ),
    ]
