from .search_engine import search_in_engine
from .page_visit import visit_page_naturally, smart_click_and_visit
from .link_extractor import extract_internal_links
from .fallback_extractors import extract_urls_from_text, extract_urls_from_meta, extract_urls_from_scripts, extract_urls_from_images
from .interceptors import intercept_route