from urllib.parse import quote_plus
from typing import List, Dict

from .general_settings import SEARCH_ENGINES_ENABLED

def get_search_engines(query: str) -> List[Dict]:
    encoded_query = quote_plus(query)
    all_engines = [
        {
            "name": "Google",
            "enabled": SEARCH_ENGINES_ENABLED.get("Google", True),
            "url": f"https://www.google.com/search?q={encoded_query}&num=30",
            "selectors": [
                'div#search a[href^="http"]:not([href*="google.com"])',
                'div.g a[href^="http"]:not([href*="google.com"])',
                'div.rc a[href^="http"]:not([href*="google.com"])',
                'h3 a[href^="http"]:not([href*="google.com"])',
                'div[data-ved] a[href^="http"]:not([href*="google.com"])',
                'div#rso a[href^="http"]:not([href*="google.com"])',
                'div.yuRUbf a[href^="http"]:not([href*="google.com"])',
                'div.cite a[href^="http"]:not([href*="google.com"])',
            ],
            "exclude_domains": ["google.com", "googleusercontent.com", "gstatic.com"],
            "wait_for_selector": 'div#search, div#rso',
            "priority_selectors": [
                'div#search a[href^="http"]:not([href*="google.com"])',
                'div.g a[href^="http"]:not([href*="google.com"])',
            ],
        },
        {
            "name": "Bing",
            "enabled": SEARCH_ENGINES_ENABLED.get("Bing", True),
            "url": f"https://www.bing.com/search?q={encoded_query}&count=30",
            "selectors": [
                'li.b_algo h2 a[href^="http"]:not([href*="bing.com"])',
                'div.b_title a[href^="http"]:not([href*="bing.com"])',
                'div#b_results a[href^="http"]:not([href*="bing.com"])',
                'div.b_algo a[href^="http"]:not([href*="bing.com"])',
                'h2 a[href^="http"]:not([href*="bing.com"])',
                'div.b_caption a[href^="http"]:not([href*="bing.com"])',
            ],
            "exclude_domains": ["bing.com", "microsoft.com"],
            "wait_for_selector": 'li.b_algo, div#b_results',
            "priority_selectors": [
                'li.b_algo h2 a[href^="http"]:not([href*="bing.com"])',
                'div.b_title a[href^="http"]:not([href*="bing.com"])',
            ],
        },
        {
            "name": "DuckDuckGo",
            "enabled": SEARCH_ENGINES_ENABLED.get("DuckDuckGo", True),
            "url": f"https://duckduckgo.com/?q={encoded_query}&kl=us-en&ia=web",
            "selectors": [
                'article[data-nrn="result"] a[href^="http"]:not([href*="duckduckgo.com"])',
                'div.result__body a.result__a[href^="http"]:not([href*="duckduckgo.com"])',
                'h2 a[href^="http"]:not([href*="duckduckgo.com"])',
                'div.result__title a[href^="http"]:not([href*="duckduckgo.com"])',
                'div#links a[href^="http"]:not([href*="duckduckgo.com"])',
                'div.results a[href^="http"]:not([href*="duckduckgo.com"])',
            ],
            "exclude_domains": ["duckduckgo.com", "duck.com"],
            "wait_for_selector": 'article[data-nrn="result"], div.result__body',
            "priority_selectors": [
                'article[data-nrn="result"] a[href^="http"]:not([href*="duckduckgo.com"])',
                'div.result__body a.result__a[href^="http"]:not([href*="duckduckgo.com"])',
            ],
        },
        {
            "name": "Yandex",
            "enabled": SEARCH_ENGINES_ENABLED.get("Yandex", True),
            "url": f"https://yandex.com/search/?text={encoded_query}",
            "selectors": [
                'li[data-cid] div.Organic h2 a.Link[href^="http"]:not([href*="yandex"])',
                'div.serp-item div.OrganicTitle a.Link[href^="http"]:not([href*="yandex"])',
                'h2 a[href^="http"]',
                'div.OrganicTitle a',
                'a.OrganicTitle-Link',
                'div[data-fast-name="organic"] a',
                'div.OrganicTitle a[href^="http"]',
                'h2.OrganicTitle a',
                'a.OrganicTitle-Link[href^="http"]',
                'div[data-fast-name="organic"] a[href^="http"]',
                'div.OrganicTitle-Link a',
                'h2.OrganicTitle-Link a',
                'div[data-cid] a[href^="http"]',
                'a[data-fast-name="organic"]',
                'div.Organic a[href^="http"]',
                'li.Organic a',
                'div.OrganicTitle a[target="_blank"]',
                'a.OrganicTitle[href^="https"]'
            ],
            "exclude_domains": ["yandex.com", "yandex.ru", "ya.ru", "yastatic.net", "yandex.st"],
            "wait_for_selector": 'div.serp-list, li[data-cid], div.content__left',
            "priority_selectors": [
                'li[data-cid] div.Organic h2 a.Link[href^="http"]:not([href*="yandex"])',
                'div.serp-item div.OrganicTitle a.Link[href^="http"]:not([href*="yandex"])',
                'h2 a[href^="http"]',
                'div.OrganicTitle a',
                'a.OrganicTitle-Link',
                'div[data-fast-name="organic"] a',
                'div.OrganicTitle a[href^="http"]',
                'h2.OrganicTitle a',
                'a.OrganicTitle-Link[href^="http"]',
                'div[data-fast-name="organic"] a[href^="http"]',
                'div.OrganicTitle-Link a',
                'h2.OrganicTitle-Link a',
                'div[data-cid] a[href^="http"]',
                'a[data-fast-name="organic"]',
                'div.Organic a[href^="http"]',
                'li.Organic a',
                'div.OrganicTitle a[target="_blank"]',
                'a.OrganicTitle[href^="https"]'
            ],
        },
        {
            "name": "Yahoo",
            "enabled": SEARCH_ENGINES_ENABLED.get("Yahoo", True),
            "url": f"https://search.yahoo.com/search?p={encoded_query}",
            "selectors": [
                'div#web ol li div.dd.algo h3.title a[href^="http"]:not([href*="yahoo.com"])',
                'div.searchCenterMiddle li div.compTitle h3 a[href^="http"]:not([href*="yahoo.com"])',
                'div[data-component="algo"] a.ac-algo[href^="http"]:not([href*="yahoo.com"])',
                'div#results div.algo h3 a[href^="http"]:not([href*="yahoo.com"])',
                'div.algo-sr a.fz-14[href^="http"]:not([href*="yahoo.com"])',
                'div.algo-sr a.ac-algo[href^="http"]:not([href*="yahoo.com"])',
                'div#right div.algo h3 a[href^="http"]:not([href*="yahoo.com"])',
                'div#sidebar div.algo h3 a[href^="http"]:not([href*="yahoo.com"])',
                'div.dd a[href^="http"]:not([href*="yahoo.com"])',
                'div.algo-sr a.ac-algo-fz[href^="http"]:not([href*="yahoo.com"])',
                'div.compTitle a[href^="http"]:not([href*="yahoo.com"])',
                'span.fz-15px',
                'div.compText a[href^="http"]:not([href*="yahoo.com"])',
                'div#main a[href^="http"]:not([href*="yahoo.com"])',
                'div#results a[href^="http"]:not([href*="yahoo.com"])',
                'div#mainline a[href^="http"]:not([href*="yahoo.com"])',
            ],
            "exclude_domains": ["yahoo.com", "search.yahoo.com", "yahoo.net"],
            "wait_for_selector": 'div#web, div.searchCenterMiddle, div#results',
            "priority_selectors": [
                'div#web ol li div.dd.algo h3.title a[href^="http"]:not([href*="yahoo.com"])',
                'div#results div.algo h3 a[href^="http"]:not([href*="yahoo.com"])',
            ],
        },
        {
            "name": "Brave",
            "enabled": SEARCH_ENGINES_ENABLED.get("Brave", True),
            "url": f"https://search.brave.com/search?q={encoded_query}&source=web",
            "selectors": [
                'div[data-type="web"] div.snippet a[href^="http"]:not([href*="brave.com"])',
                'div.fdb-container div.snippet-title a[href^="http"]:not([href*="brave.com"])',
                'div#results a.result-header[href^="http"]:not([href*="brave.com"])',
                'article[data-type="web"] a[href^="http"]:not([href*="brave.com"])',
                'div[data-result="web"] a[href^="http"]:not([href*="brave.com"])',
                'div.snippet__body a[href^="http"]:not([href*="brave.com"])',
                'div[data-type="infobox"] a[href^="http"]:not([href*="brave.com"])',
                'div.infobox a[href^="http"]:not([href*="brave.com"])',
                'div.card a[href^="http"]:not([href*="brave.com"])',
                'div.result-card a[href^="http"]:not([href*="brave.com"])',
                'div#results a[href^="http"]:not([href*="brave.com"])',
                'main a[href^="http"]:not([href*="brave.com"])',
            ],
            "exclude_domains": ["brave.com", "search.brave.com", "brave.net"],
            "wait_for_selector": 'div#results, div[data-type="web"], article[data-type="web"]',
            "priority_selectors": [
                'div[data-type="web"] div.snippet a[href^="http"]:not([href*="brave.com"])',
                'article[data-type="web"] a[href^="http"]:not([href*="brave.com"])',
            ],
        },
        {
            "name": "Ecosia",
            "enabled": SEARCH_ENGINES_ENABLED.get("Ecosia", True),
            "url": f"https://www.ecosia.org/search?q={encoded_query}",
            "selectors": [
                'section.mainline div.result a.result-url[href^="http"]:not([href*="ecosia.org"])',
                'div.result__title a[href^="http"]:not([href*="ecosia.org"])',
                'article.result a[href^="http"]:not([href*="ecosia.org"])',
                'div[data-testid="result"] a[href^="http"]:not([href*="ecosia.org"])',
                'article[data-result="web"] a[href^="http"]:not([href*="ecosia.org"])',
                'div.web-results a[href^="http"]:not([href*="ecosia.org"])',
                'div.ads-ad a[href^="http"]:not([href*="ecosia.org"])',
                'div.result--ad a[href^="http"]:not([href*="ecosia.org"])',
                'div.news-result a[href^="http"]:not([href*="ecosia.org"])',
                'div.image-result a[href^="http"]:not([href*="ecosia.org"])',
                'div.results a[href^="http"]:not([href*="ecosia.org"])',
                'main a[href^="http"]:not([href*="ecosia.org"])',
                'section a[href^="http"]:not([href*="ecosia.org"])',
                'div.result-url',
                'span.result-url',
            ],
            "exclude_domains": ["ecosia.org", "bing.com"],
            "wait_for_selector": 'section.mainline, div.result, div.web-results',
            "priority_selectors": [
                'section.mainline div.result a.result-url[href^="http"]:not([href*="ecosia.org"])',
                'div[data-testid="result"] a[href^="http"]:not([href*="ecosia.org"])',
                'div.result__title a[href^="http"]:not([href*="ecosia.org"])',
                'article.result a[href^="http"]:not([href*="ecosia.org"])',
                'div.web-results a[href^="http"]:not([href*="ecosia.org"])',
                'section.mainline a.result-url[href^="https"]:not([href*="ecosia.org"])',
                'div[data-testid="result"] a[href^="https"]:not([href*="ecosia.org"])',
                'div.result__title a[target="_blank"]:not([href*="ecosia.org"])',
                'article[data-result="web"] a[href^="http"]:not([href*="ecosia.org"])',
                'div.result-item a[href^="http"]:not([href*="ecosia.org"])',
                'h3.result__title a[href^="http"]:not([href*="ecosia.org"])',
                'a.result-url[target="_blank"]:not([href*="ecosia.org"])',
                'div[data-result] a[href^="http"]:not([href*="ecosia.org"])',
                'section a[href^="http"]:not([href*="ecosia.org"])'
            ],
        },
        {
            "name": "Startpage",
            "enabled": SEARCH_ENGINES_ENABLED.get("Startpage", True),
            "url": f"https://www.startpage.com/sp/search?query={encoded_query}",
            "selectors": [
                'section.w-gl div.w-gl__result a[href^="http"]:not([href*="startpage.com"])',
                'div.w-gl__result a.result-link[href^="http"]:not([href*="startpage.com"])',
                'div.result a[href^="http"]:not([href*="startpage.com"])',
                'article.search-result a[href^="http"]:not([href*="startpage.com"])',
                'div.search-result a[href^="http"]:not([href*="startpage.com"])',
                'main a[href^="http"]:not([href*="startpage.com"])',
                'div#results a[href^="http"]:not([href*="startpage.com"])',
            ],
            "exclude_domains": ["startpage.com", "startmail.com"],
            "wait_for_selector": 'section.w-gl, div.w-gl__result, div#results',
            "priority_selectors": [
                'section.w-gl div.w-gl__result a[href^="http"]:not([href*="startpage.com"])',
                'div.w-gl__result a.result-link[href^="http"]:not([href*="startpage.com"])',
                'div.w-gl__result a[href^="https"]:not([href*="startpage.com"])',
                'article.search-result a[href^="http"]:not([href*="startpage.com"])',
                'div.search-result a[href^="http"]:not([href*="startpage.com"])',
                'section.w-gl a[href^="http"]:not([href*="startpage.com"])',
                'div.w-gl__result a[target="_blank"]:not([href*="startpage.com"])',
                'div#results a[href^="http"]:not([href*="startpage.com"])',
                'main a[href^="http"]:not([href*="startpage.com"])',
                'div.search-result a[target="_blank"]:not([href*="startpage.com"])',
                'article.search-result a[href^="https"]:not([href*="startpage.com"])',
                'a.result-link[target="_blank"]:not([href*="startpage.com"])'
            ],
        },
    ]
    
    return [engine for engine in all_engines if engine.get("enabled", False)]